#
# YAML
#
# Файл настроек
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# Список используемых JS файлов
# / Относительно корневой папки с JS скриптами
#
include:
  - ext/ux/grid/plugin/editing.js

#
# Список модулей, которые используются
# / Перечисляются имена модулей
#
modules:
  - common/lib/modelslist
  - x/obj/package
  - x/obj/fee
  - x/obj/tariff
  - x/obj/tariff_option
  - x/obj/module
  - x/obj/right_level

#
# Список JS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
js:
  - js/module.js
  - js/view/list.js
  - js/control/list.js
  - js/view/tabs/props.js
  - js/view/panel.js
  - js/control/tabs/props.js
  - js/control/panel.js

#
# Список CSS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
css:
  - css/style.css
  - css/checkheader.css

#
# Путь к языковым файлам.
# / {0} заменяется на алиас (ru, en, de и т.д.)
# / Относительно папки в которой находится данный файл конфигурации
#
lang:
  - lang/{{language}}.js
