#
# YAML
#
# Файл настроек
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# Список используемых JS файлов
# / Относительно корневой папки с JS скриптами
#
include:
  - /o/kernel/proxy/period.js

#
# Список модулей, которые используются
# / Перечисляются имена модулей
#
modules:
  - common/lib/periodtoolbar
  - common/lib/events
#  - obj/works
  - n/obj/work
  - obj/events
  - x/obj/group_mon_device
  - x/obj/user
  - mon/obj/device
  - mon/obj/geofence

#
# Список JS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
js:
  - js/view/panel.js
  - js/control/panel.js
  - js/control/eventspanel.js
  - js/module.js

#
# Список CSS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
css:
  - css/style.css

#
# Путь к языковым файлам.
# / {0} заменяется на алиас (ru, en, de и т.д.)
# / Относительно папки в которой находится данный файл конфигурации
#
lang:
  - lang/{{language}}.js
