#
# YAML
#
# Файл настроек
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# Список используемых JS файлов
# / Относительно корневой папки с JS скриптами
#
include:

#
# Список модулей, которые используются
# / Перечисляются имена модулей
#
modules:
  - common/lib/modelslist
  - common/lib/billing
  - x/lib/user
  - mon/lib/device
  - dn/lib/warehouses
  - x/obj/firm
  - common/lib/companyrequisites
  - common/lib/company
  - mon/lib/device

#
# Список JS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
js:
  - js/model/tariffenabled.js
  - js/view/tabs/proxy.js
  - js/view/tabs/tariffs.js
  - js/view/tabs/settings.js
  - js/view/tabs/billing.js
  - js/view/tabs/users.js
  - js/view/tabs/device.js
  - js/view/panel.js
  - js/module.js

#
# Список CSS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
css:
  - css/style.css

#
# Путь к языковым файлам.
# / {0} заменяется на алиас (ru, en, de и т.д.)
# / Относительно папки в которой находится данный файл конфигурации
#
lang:
  - lang/{{language}}.js
