#
# YAML
#
# Файл настроек
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# Список используемых JS файлов
# / Относительно корневой папки с JS скриптами
#
include:
  - o/ux/grouplistdevices.js

#
# Список модулей, которые используются
# / Перечисляются имена модулей
#
modules:
  - mon/obj/device
  - x/obj/group_mon_device
  - common/lib/grouplist
  - common/lib/objectsgroupslist

#
# Список JS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
js:
  - js/view/panel.js
  - js/control/panel.js
  - js/control/groups.js
  - js/control/objects.js

#
# Список CSS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
css:
  - css/style.css
#
# Путь к языковым файлам.
# / {0} заменяется на алиас (ru, en, de и т.д.)
# / Относительно папки в которой находится данный файл конфигурации
#
lang:
  - lang/{{language}}.js
