#
# YAML
#
# Configuration
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# List of JS files used in module
# / Relative to root folder of JS files
#
include:
  - ext/ux/grid/printer.js
  - o/kernel/proxy/store.js
  - o/kernel/ui/searchgrid.js
  - ext/selection/checkboxmodel.js

#
# List of modules, wich are used in this module
# / Here are listed the names of modules
#
modules:
  - common/lib/companyrequisites
  - dn/obj/doc
  - dn/obj/offer
  - common/lib/uploadpanel
  - common/lib/contactview
  - dn/obj/supplier_account

#
# List of JS files, included in this module
# / Relative to the folder that contains this configuration file
#
js:
  - js/model/phone.js
  - js/model/email.js
  - js/view/mailingwindow.js
  - js/view/tabs/info.js
  - js/view/tabs/docs.js
  - js/view/list.js
  - js/view/view.js
  - js/view/panel.js
  - js/control/mailingwindow.js
  - js/control/tabs/info.js
  - js/control/tabs/docs.js
  - js/control/list.js
  - js/control/view.js
  - js/control/panel.js
  - js/module.js

#
# List of CSS files, wich are plugged in this module
# / Relative to the folder that contains this configuration file
#
css:
  - css/style.css

#
# The path to language files
# / {language} is replaced by the alias (ru, en, de и т.д.)
# / Relative to the folder that contains this configuration file
#
lang:
  - lang/{{language}}.js