#
# YAML
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# Список используемых JS файлов
# / Относительно корневой папки с JS скриптами
#
include:
  - o/kernel/proxy/ajax.js
  - o/kernel/proxy/store.js
  - o/kernel/ui/searchgrid.js

#
# Список модулей, которые используются
# / Перечисляются имена модулей
#
modules:
  - common/lib/regionchooser
  - dn/obj/measure

#
# Список JS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
js:
  - js/view/panel.js
  - js/control/panel.js
  - js/model/model-product.js
  - js/model/store-product.js
  - js/module.js

#
# Список CSS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
css:
  - css/style.css

#
# Путь к языковым файлам.
# / {0} заменяется на алиас (ru, en, de и т.д.)
# / Относительно папки в которой находится данный файл конфигурации
#
lang:
  - lang/{{language}}.js
