#
# YAML
#
# Файл настроек
#
# @project    Maprox <http://www.maprox.net>
# @copyright  2012, Maprox LLC
# ---------------------------------------------------------------------------

#
# Список используемых JS файлов
# / Относительно корневой папки с JS скриптами
#
include:

# 
# Список модулей, которые используются
# / Перечисляются имена модулей
#
modules:

#
# Список JS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
js:
  - js/view/firmsearch.js
  - js/control/firmsearch.js
  - js/view/usersearch.js
  - js/control/usersearch.js
  - js/view/panel.js
  - js/control/panel.js

#
# Список CSS файлов, подключаемых в данном модуле
# / Относительно папки в которой находится данный файл конфигурации
#
css:
  - css/style.css
#
# Путь к языковым файлам.
# / {0} заменяется на алиас (ru, en, de и т.д.)
# / Относительно папки в которой находится данный файл конфигурации
#
lang:
  - lang/{{language}}.js